apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::391378411314:role/hello-protos-eks-node-group-role
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::391378411314:role/hello-protos-build-role
      username: codebuild
      groups:
        - system:masters
kind: ConfigMap
metadata:
  creationTimestamp: "2020-05-12T13:15:29Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2687"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 01826a53-188c-4495-b3f7-8d04a099bcdd