apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-$IMAGE_TAG
  labels:
    app: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - image: $IMAGE:$IMAGE_TAG
        imagePullPolicy: Always
        name: hello
        ports:
        - containerPort: 8080
---     
apiVersion: v1
kind: Service
metadata:
  name: hello-$IMAGE_TAG
spec:
  selector:
    app: hello
  ports:
    - port: 8080
  #type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-$IMAGE_TAG
spec:
  rules:
    - host: hello-$IMAGE_TAG.d3vblog.com
      http:
        paths:
          - backend:
              serviceName: hello-$IMAGE_TAG
              servicePort: 8080
            path: /

