# Create an EBS volume and reference the volumeID below
# Run the container with: kubectl apply -f ebs-disk.yml
# Check logs: kubectl logs busybox-69cffb969f-zc6vm
# Then delete the container or the deploy
# Reapply the manisfest, you should see that the file time.log did persist.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv001
  labels:
    type: amazonEBS 
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-05e43a268e6e93e00
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc001
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: busybox
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
          - ls -la /ebs;
            echo `date` >> /ebs/time.log;
            cat /ebs/time.log;
        volumeMounts:
        - mountPath: "/ebs"
          name: ebs
      volumes:
        - name: ebs
          persistentVolumeClaim:
            claimName: pvc001